"""empty message

Revision ID: 0c7a25cec9bc
Revises: 0e5313794fc7
Create Date: 2018-05-04 17:46:14.546740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c7a25cec9bc'
down_revision = '0e5313794fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('discrete', sa.Boolean(), nullable=False))
    op.alter_column('items', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('items', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('items', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('items', 'discrete')
    # ### end Alembic commands ###
