"""empty message

Revision ID: 0e5313794fc7
Revises: 00d19b7aea8d
Create Date: 2018-05-04 17:34:03.002773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e5313794fc7'
down_revision = '00d19b7aea8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('measurement', sa.String(length=10), nullable=True))
    op.add_column('items', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('items', 'desc',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('items', 'type',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('items', 'type',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('items', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('items', 'desc',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_column('items', 'price')
    op.drop_column('items', 'measurement')
    # ### end Alembic commands ###
